# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 03:45
from __future__ import unicode_literals

import apps.utility.toolbelt
import django.core.validators
from django.db import migrations, models
import oscar.core.validators
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20160504_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sample_audio',
            new_name='sample_ogg',
        ),
        migrations.AddField(
            model_name='product',
            name='sample_mp3',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=apps.utility.toolbelt.upload_file),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='code',
            field=models.SlugField(max_length=128, validators=[django.core.validators.RegexValidator(message="Code can only contain the letters a-z, A-Z, digits, and underscores, and can't start with a digit.", regex='^[a-zA-Z_][0-9a-zA-Z_]*$'), oscar.core.validators.non_python_keyword], verbose_name='Code'),
        ),
    ]
