# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20161112_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='mididownloadurl',
            name='downloads_left',
            field=models.IntegerField(default=0),
        ),
    ]
