# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20170805_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='midi_file',
            new_name='upload',
        ),
    ]
