# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 20:11
from __future__ import unicode_literals

import apps.utility.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20171202_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_audio',
            field=models.FileField(blank=True, help_text='The full audio for an audio file, this field will be automatically set.', max_length=1024, null=True, upload_to=apps.utility.files.upload_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='sample_mp3',
            field=models.FileField(blank=True, help_text='The sample audio for an audio file, this field will be automatically set.', max_length=1024, null=True, upload_to=apps.utility.files.upload_file),
        ),
        migrations.AlterField(
            model_name='product',
            name='sample_ogg',
            field=models.FileField(blank=True, help_text='The sample ogg audio for an audio file, this field will be automatically set.', max_length=1024, null=True, upload_to=apps.utility.files.upload_file),
        ),
    ]
