# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20150807_1725'),
        ('customer', '0002_auto_20160109_2001'),
    ]

    operations = [
    ]
