# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20160819_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stripe_id', models.CharField(max_length=50, unique=True)),
                ('card_fingerprint', models.CharField(blank=True, max_length=200)),
                ('card_last_4', models.CharField(blank=True, max_length=4)),
                ('card_kind', models.CharField(blank=True, max_length=50)),
                ('card_exp_month', models.PositiveIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
