# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0001_squashed_0007_for_custom_subscriber_model'),
        ('customer', '0005_gueststripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststripecustomer',
            name='default_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_customers', to='djstripe.Charge'),
        ),
    ]
